# Generated by Django 5.2.2 on 2025-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="another_city",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="其他感兴趣城市"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="card_id",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="电子名片标识"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="certificates",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="工作证明列表/id"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="contract",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="工作协议"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="delivery_record",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="投递记录列表/投递岗位标识列表"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="home_page_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="主页分类"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="homepage_activity",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="主页活跃度"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="homepage_hot",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="主页热度"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ideal_area",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="期望行业"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ideal_city",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="期望工作城市"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="money",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="用户余额"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="priority",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="用户权限等级"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="project_id_list",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="我的项目标识列表"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="resume_id_list",
            field=models.JSONField(
                blank=True, default=list, null=True, verbose_name="简历标识列表"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="个性签名"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="workbench",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="是否已开通工作台"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="用户名/电话/邮箱"
            ),
        ),
    ]
