# Generated by Django 5.2.2 on 2025-07-25 03:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_user_another_city_user_card_id_user_certificates_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEvaluate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=50, null=True)),
                ("company", models.CharField(blank=True, max_length=100, null=True)),
                ("PostingID", models.CharField(blank=True, max_length=50, null=True)),
                ("rate", models.IntegerField(blank=True, default=0, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("createAt", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "用户评价",
                "verbose_name_plural": "用户评价",
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("permission", models.JSONField(blank=True, default=dict, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("desc", models.TextField(blank=True, null=True)),
                ("photo", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("birthday", models.CharField(blank=True, max_length=20, null=True)),
                ("education", models.JSONField(blank=True, default=list, null=True)),
                (
                    "graduationYear",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "workExperience",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "projectExperience",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("prize", models.JSONField(blank=True, default=list, null=True)),
                ("scientific", models.JSONField(blank=True, default=list, null=True)),
                ("introduction", models.TextField(blank=True, null=True)),
                ("skill", models.JSONField(blank=True, default=list, null=True)),
                ("resumeFile", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "简历",
                "verbose_name_plural": "简历",
            },
        ),
    ]
